const API_URL1 = 'http://localhost:5000/api/'
const API_URL = 'https://bigbox-backend.herokuapp.com/api/'

export const GET_ALL_ITEM = API_URL + 'item'
export const GET_ALL_ITEMS = API_URL + 'item/all'
export const ADD_ITEM = API_URL + 'item/store'
export const GET_ITEM = API_URL + 'item/show'
export const UPDATE_ITEM = API_URL + 'item/update'
export const DELETE_ITEM = API_URL + 'item/delete'
export const LOGIN_USER = API_URL + 'login'
export const LOGOUT_USER = API_URL + 'logout'
export const REGISTER_USER = API_URL + 'register'
